export const KEYS = {
    translations_list: "translations_list",
    constants_list: "constants_list",
    warehouses_list: "warehouses_list",
    warehouse_workers_list: "warehouse_workers_list",
    warehouse_sections_list: "warehouse_sections_list",
    team_leads_list: "team_leads_list",
    categories_list: "categories_list",
    products_list: "products_list",
    managers_list: "managers_list",
    dealers_list: "dealers_list",
    couriers_list: "couriers_list",
    clients_list: "clients_list",
    client_types_list: "client_types_list",
    orders_list: "orders_list",
};
